name: Swipe Events Manager
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm start
